// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var Faucet, SlowFaucet, faucet, stream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  stream = require('stream');

  exports.Faucet = Faucet = (function(_super) {
    __extends(Faucet, _super);

    function Faucet(buf) {
      this.buf = buf;
      Faucet.__super__.constructor.apply(this, arguments);
    }

    Faucet.prototype._read = function(sz) {
      this.push(this.buf);
      return this.buf = null;
    };

    return Faucet;

  })(stream.Readable);

  exports.SlowFaucet = SlowFaucet = (function(_super) {
    __extends(SlowFaucet, _super);

    function SlowFaucet(_arg) {
      this.buf = _arg.buf, this.blocksize = _arg.blocksize, this.wait_msec = _arg.wait_msec;
      SlowFaucet.__super__.constructor.call(this);
      this._i = 0;
    }

    SlowFaucet.prototype._read = function(n) {
      var buf, end;
      buf = null;
      if (this.buf == null) {

      } else if (this.blocksize == null) {
        buf = this.buf;
        this.buf = null;
      } else if (this._i < this.buf.length) {
        end = this._i + this.blocksize;
        buf = this.buf.slice(this._i, end);
        this._i = end;
      }
      return this.push(buf);
    };

    return SlowFaucet;

  })(stream.Readable);

  exports.faucet = faucet = function(_arg, cb) {
    var buf, done, f, stream;
    buf = _arg.buf, stream = _arg.stream;
    f = new Faucet(buf);
    f.pipe(stream);
    done = function(err) {
      var tmp;
      if ((tmp = cb) != null) {
        cb = null;
        return tmp(err);
      }
    };
    stream.on('finish', function() {
      return done(null);
    });
    return stream.on('error', function(err) {
      return done(err);
    });
  };

}).call(this);
