// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var k, mod, mods, v, _i, _len;

  mods = [require('./drain'), require('./faucet'), require('./transform')];

  for (_i = 0, _len = mods.length; _i < _len; _i++) {
    mod = mods[_i];
    for (k in mod) {
      v = mod[k];
      exports[k] = v;
    }
  }

}).call(this);
